# ----------------------------------------
# Services
# ----------------------------------------
services:
  # --------------------------------------
  # Jenkins Node Service
  # --------------------------------------
  jenkins-node:
    build:
      context: .                                          # Context for the build - the same directory as docker-compose.yml
      dockerfile: Dockerfile_jenkins_node
    container_name: jenkins_node
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/agent:/home/jenkins/agent                       # Mount the Jenkins agent directory
    environment:
      - JENKINS_URL=http://192.168.22.7:8082              # Jenkins server URL
      - JENKINS_SECRET=<jenkins_encryption_key>           # Jenkins agent secret
      - JENKINS_AGENT_NAME=Test                           # Jenkins agent name
    working_dir: /home/jenkins                               # Default working directory inside the container
