version: '3'

services:
  esp32_build:
    image: my-esp32-image:latest
    container_name: esp32_builder
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./scripts:/usr/local/scripts           # Mount the scripts directory into the container
      - ./artifacts:/usr/local/artifacts       # Mount the temporary directory for build artifacts
      - ./docker/scripts/tmp:/usr/local/build  # Mount location for build project
    environment:
      - ESP_IDF_PATH=/opt/esp/idf     # Environment variable for ESP-IDF
    working_dir: /workspace           # Default working directory inside the container
    entrypoint: ["/bin/bash", "-c", "source /opt/esp/idf/export.sh && /usr/local/scripts/build.sh"]  # Set up ESP-IDF environment first
    tty: true                         # Enable interactive terminal if needed

networks:
  default:
    driver: bridge