version: '3'

services:
  esp32_build:
    image: my-esp32-image:latest
    container_name: esp32_builder
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./docker/scripts:/usr/local/scripts  # Mount the scripts directory into the container
      - ./artifacts:/usr/local/artifacts     # Mount the temporary directory for build artifacts
      - "${ESP_PROJECT_DIR}:/usr/local/build"  # Dynamic mount location for build project
    environment:
      - ESP_IDF_PATH=/opt/esp/idf            # Environment variable for ESP-IDF
    working_dir: /workspace                  # Default working directory inside the container
    entrypoint: ["/bin/bash", "-c", "source /opt/esp/idf/export.sh && tail -f /dev/null"]
    tty: true                                # Enable interactive terminal if needed

networks:
  default:
    driver: bridge